import requests

def fetch_onc_data(api_url: str):
    """
    Takes a full API URL string (generated by the LLM) and returns the response data.
    """
    try:
        response = requests.get(api_url)
        response.raise_for_status()  # Raise an exception for HTTP errors
        data = response.json()
        print("API response:")
        print(data)
        return data
    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
    except ValueError:
        print("Failed to parse JSON response.")
    return None

# # Example LLM-generated API call
# llm_generated_api_call = "https://data.oceannetworks.ca/api/locations?locationCode=CBYIP&token=5e3aec6d-8ed0-49bc-9e96-7980704c17ef"
# api_call_2 = "https://data.oceannetworks.ca/api/properties?locationCode=CBYIP&deviceCategoryCode=ICEPROFILER&token=5e3aec6d-8ed0-49bc-9e96-7980704c17ef"

# # Fetch and print results
# fetch_onc_data(api_call_2)
